import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AppShell } from "@/components/app-shell";
import { AccountGuard } from "@/components/account-guard";
import { Progress } from "@/components/ui/progress";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { TASK_STATUS_LABELS,TASK_STATUS_ORDER,daysUntil } from "@/lib/noivahub";

export const Route=createFileRoute("/_authenticated/meu-casamento")({head:()=>({meta:[{title:"Meu Casamento — NoivaHub"},{name:"description",content:"Checklist e progresso do seu planejamento de casamento."},{property:"og:title",content:"Meu Casamento — NoivaHub"},{property:"og:description",content:"Checklist inteligente do seu casamento."}]}),component:MeuCasamento});
function MeuCasamento(){const {user}=Route.useRouteContext();const qc=useQueryClient();const {data}=useQuery({queryKey:["wedding-tasks",user.id],queryFn:async()=>{const [{data:t},{data:b}]=await Promise.all([supabase.from("wedding_tasks").select("id,status,categories:category_id(id,name,emoji,slug)").eq("bride_id",user.id),supabase.from("brides").select("wedding_date").eq("id",user.id).maybeSingle()]);return{tasks:t??[],date:b?.wedding_date}}});const tasks=data?.tasks??[];const hired=tasks.filter(t=>t.status==="contratado").length;const progress=tasks.length?Math.round(hired/tasks.length*100):0;async function update(id:string,status:string){await supabase.from("wedding_tasks").update({status:status as "nao_iniciado"|"pesquisando"|"contato"|"negociacao"|"contratado"}).eq("id",id);qc.invalidateQueries({queryKey:["wedding-tasks"]});}return <AccountGuard type="bride">{()=> <AppShell type="bride"><div className="mx-auto max-w-5xl p-5 md:p-10"><h1 className="font-display text-4xl">Meu Casamento ❤️</h1><p className="mt-2 text-muted-foreground">{daysUntil(data?.date)===null?"Defina a data do seu casamento no perfil.":`Faltam ${daysUntil(data?.date)} dias para o grande dia.`}</p><div className="surface mt-6 p-6"><div className="flex justify-between"><span>Seu casamento está {progress}% planejado.</span><span className="text-sm text-muted-foreground">{hired}/{tasks.length}</span></div><Progress value={progress} className="mt-3"/></div><div className="mt-6 space-y-3">{tasks.map(t=><div key={t.id} className="surface flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="flex-1"><p className="font-medium">{t.categories?.emoji} {t.categories?.name}</p><p className="text-xs text-muted-foreground">{TASK_STATUS_LABELS[t.status]}</p></div><Select value={t.status} onValueChange={v=>update(t.id,v)}><SelectTrigger className="w-full sm:w-48"><SelectValue/></SelectTrigger><SelectContent>{TASK_STATUS_ORDER.map(s=><SelectItem key={s} value={s}>{TASK_STATUS_LABELS[s]}</SelectItem>)}</SelectContent></Select><Button asChild variant="outline" size="sm"><Link to="/fornecedores/$categoria" params={{categoria:t.categories?.slug??"outros"}}>Encontrar fornecedor</Link></Button></div>)}</div>{tasks.length===0?<div className="surface mt-6 p-10 text-center"><p className="font-display text-2xl">Seu checklist ainda está vazio</p><Button asChild className="mt-4"><Link to="/onboarding">Criar planejamento</Link></Button></div>:null}</div></AppShell>}</AccountGuard>}
