import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Heart, CheckCircle2, Clock3, MessageCircle } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AccountGuard } from "@/components/account-guard";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { daysUntil } from "@/lib/noivahub";

export const Route = createFileRoute("/_authenticated/noiva")({
  head: () => ({ meta: [
    { title: "Painel da noiva — NoivaHub" }, { name: "description", content: "Acompanhe o progresso do seu casamento." },
    { property: "og:title", content: "Painel da noiva — NoivaHub" }, { property: "og:description", content: "Seu casamento organizado em um só lugar." },
  ]}), component: NoivaDashboard,
});
function NoivaDashboard(){const {user}=Route.useRouteContext(); const {data}=useQuery({queryKey:["bride-dashboard",user.id],queryFn:async()=>{const [{data:b},{data:t},{count:f},{count:l}]=await Promise.all([supabase.from("brides").select("*").eq("id",user.id).maybeSingle(),supabase.from("wedding_tasks").select("status").eq("bride_id",user.id),supabase.from("favorites").select("id",{count:"exact",head:true}).eq("user_id",user.id),supabase.from("leads").select("id",{count:"exact",head:true}).eq("bride_id",user.id)]);return{bride:b,tasks:t??[],favorites:f??0,leads:l??0}}}); const total=data?.tasks.length??0;const hired=data?.tasks.filter(t=>t.status==="contratado").length??0;const progress=total?Math.round(hired/total*100):0;const days=daysUntil(data?.bride?.wedding_date); return <AccountGuard type="bride">{account=><AppShell type="bride"><div className="mx-auto max-w-6xl p-5 md:p-10"><p className="text-sm text-muted-foreground">Meu painel</p><h1 className="font-display text-4xl">Olá, {account.profile?.full_name?.split(" ")[0] ?? "noiva"} ❤️</h1>{!data?.bride?.onboarded?<div className="surface mt-8 p-6"><h2 className="font-display text-2xl">Vamos criar seu planejamento?</h2><p className="mt-2 text-sm text-muted-foreground">Responda cinco perguntas rápidas para gerar seu checklist.</p><Button asChild className="mt-4"><Link to="/onboarding">Começar</Link></Button></div>:<><div className="surface mt-8 p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-muted-foreground">Contagem regressiva</p><p className="font-display text-3xl">{days===null?"Defina a data":days>=0?`Faltam ${days} dias para o grande dia.`:"O grande dia chegou!"}</p></div><div className="text-right"><p className="text-sm text-muted-foreground">Progresso geral</p><p className="font-display text-3xl">{progress}%</p></div></div><Progress value={progress} className="mt-5"/><p className="mt-2 text-sm text-muted-foreground">Você já organizou {hired} de {total} categorias.</p></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{l:"Favoritos",v:data?.favorites??0,i:Heart},{l:"Contatados",v:data?.leads??0,i:MessageCircle},{l:"Contratados",v:hired,i:CheckCircle2},{l:"Pendentes",v:total-hired,i:Clock3}].map(x=><div key={x.l} className="surface p-5"><x.i className="size-5 text-gold"/><p className="mt-4 font-display text-3xl">{x.v}</p><p className="text-sm text-muted-foreground">{x.l}</p></div>)}</div><div className="mt-8 flex flex-wrap gap-3"><Button asChild><Link to="/meu-casamento">Abrir Meu Casamento</Link></Button><Button asChild variant="outline"><Link to="/fornecedores">Encontrar fornecedores</Link></Button></div></>}</div></AppShell>}</AccountGuard>}
