import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { AccountGuard } from "@/components/account-guard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/meu-perfil")({head:()=>({meta:[{title:"Meu perfil — NoivaHub"},{name:"description",content:"Atualize os dados do seu casamento e sua conta."},{property:"og:title",content:"Meu perfil — NoivaHub"},{property:"og:description",content:"Gerencie sua conta NoivaHub."}]}),component:Profile});
function Profile(){const{user}=Route.useRouteContext();return <AccountGuard type="bride">{a=><Editor userId={user.id} account={a}/>}</AccountGuard>}function Editor({userId,account}:{userId:string;account:NonNullable<ReturnType<typeof import("@/hooks/useAuth").useAccount>["data"]>}){const[f,setF]=useState({full_name:"",phone:"",city:"",state:"",partner_name:"",wedding_date:"",guests:"",budget:""});useEffect(()=>{async function load(){const{data:b}=await supabase.from("brides").select("*").eq("id",userId).maybeSingle();setF({full_name:account.profile?.full_name??"",phone:account.profile?.phone??"",city:account.profile?.city??"",state:account.profile?.state??"",partner_name:b?.partner_name??"",wedding_date:b?.wedding_date??"",guests:String(b?.guests??""),budget:String(b?.budget??"")})}load()},[userId,account]);async function save(){const[{error:p},{error:b}]=await Promise.all([supabase.from("profiles").update({full_name:f.full_name.trim().slice(0,100),phone:f.phone.trim().slice(0,30),city:f.city.trim().slice(0,100),state:f.state.trim().slice(0,2).toUpperCase()}).eq("id",userId),supabase.from("brides").update({partner_name:f.partner_name.trim().slice(0,100),wedding_date:f.wedding_date||null,guests:f.guests?Number(f.guests):null,budget:f.budget?Number(f.budget):null}).eq("id",userId)]);p||b?toast.error((p??b)?.message):toast.success("Perfil atualizado.")}const fields=[...[["full_name","Seu nome","text"],["partner_name","Nome do parceiro ou parceira","text"],["phone","Telefone","tel"],["wedding_date","Data do casamento","date"],["city","Cidade","text"],["state","Estado (UF)","text"],["guests","Convidados","number"],["budget","Orçamento (R$)","number"]]] as const;return <AppShell type="bride"><div className="mx-auto max-w-3xl p-5 md:p-10"><h1 className="font-display text-4xl">Meu perfil</h1><div className="surface mt-6 grid gap-5 p-6 sm:grid-cols-2">{fields.map(([k,l,t])=><div key={k}><Label>{l}</Label><Input type={t} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></div>)}<Button onClick={save} className="sm:col-span-2">Salvar perfil</Button></div></div></AppShell>}
