import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AppShell } from "@/components/app-shell";
import { AccountGuard } from "@/components/account-guard";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { LEAD_STATUS_LABELS } from "@/lib/noivahub";
export const Route=createFileRoute("/_authenticated/painel/leads")({head:()=>({meta:[{title:"Leads — NoivaHub"},{name:"description",content:"Gerencie as oportunidades recebidas pelo seu perfil."},{property:"og:title",content:"Leads — NoivaHub"},{property:"og:description",content:"Oportunidades do seu negócio."}]}),component:Leads});
function Leads(){return <AccountGuard type="vendor">{a=><LeadsList vendorId={a.vendorId}/>}</AccountGuard>}
function LeadsList({vendorId}:{vendorId:string|null}){const qc=useQueryClient();const {data=[]}=useQuery({queryKey:["vendor-leads",vendorId],enabled:!!vendorId,queryFn:async()=>{const {data}=await supabase.from("leads").select("id,bride_name,city,state,wedding_date,message,status,created_at,categories:category_id(name)").eq("vendor_id",vendorId??"").order("created_at",{ascending:false});return data??[]}});async function update(id:string,status:string){await supabase.from("leads").update({status:status as "novo"|"contatado"|"negociacao"|"fechado"|"perdido"}).eq("id",id);qc.invalidateQueries({queryKey:["vendor-leads"]});}return <AppShell type="vendor"><div className="mx-auto max-w-5xl p-5 md:p-10"><h1 className="font-display text-4xl">Leads recebidos</h1><p className="mt-2 text-muted-foreground">Organize cada oportunidade do primeiro contato ao fechamento.</p><div className="mt-6 space-y-3">{data.map(l=><div key={l.id} className="surface grid gap-4 p-5 md:grid-cols-[1fr_190px]"><div><p className="font-medium">{l.bride_name??"Noiva interessada"}</p><p className="text-sm text-muted-foreground">{l.categories?.name} · {l.city??"Cidade não informada"}{l.state?` - ${l.state}`:""}</p>{l.wedding_date&&<p className="mt-1 text-xs text-muted-foreground">Casamento: {new Date(`${l.wedding_date}T12:00:00`).toLocaleDateString("pt-BR")}</p>}<p className="mt-3 text-sm">{l.message}</p></div><Select value={l.status} onValueChange={v=>update(l.id,v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(LEAD_STATUS_LABELS).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div>)}{data.length===0&&<div className="surface p-10 text-center text-muted-foreground">Seus novos contatos aparecerão aqui.</div>}</div></div></AppShell>}
