import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { Eye, MessageCircle, MousePointer2, Star } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AccountGuard } from "@/components/account-guard";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { VENDOR_STATUS_LABELS } from "@/lib/noivahub";
export const Route=createFileRoute("/_authenticated/painel")({head:()=>({meta:[{title:"Painel do fornecedor — NoivaHub"},{name:"description",content:"Acompanhe seu perfil, leads e desempenho no NoivaHub."},{property:"og:title",content:"Painel do fornecedor — NoivaHub"},{property:"og:description",content:"Gestão do seu negócio no NoivaHub."}]}),component:Painel});
function Painel(){return <AccountGuard type="vendor">{account=><Vendor account={account}/>}</AccountGuard>}
function Vendor({account}:{account:NonNullable<ReturnType<typeof import("@/hooks/useAuth").useAccount>["data"]>}){const {data}=useQuery({queryKey:["vendor-dashboard",account.vendorId],enabled:!!account.vendorId,queryFn:async()=>{const [{data:v},{count:leads},{count:reviews}]=await Promise.all([supabase.from("vendors").select("views,whatsapp_clicks,rating,reviews_count,company_name,status").eq("id",account.vendorId??"").maybeSingle(),supabase.from("leads").select("id",{count:"exact",head:true}).eq("vendor_id",account.vendorId??""),supabase.from("reviews").select("id",{count:"exact",head:true}).eq("vendor_id",account.vendorId??"")]);return{v,leads:leads??0,reviews:reviews??0}}});return <AppShell type="vendor"><div className="mx-auto max-w-6xl p-5 md:p-10"><p className="text-sm text-muted-foreground">Painel do fornecedor</p><h1 className="font-display text-4xl">Olá, {account.profile?.full_name?.split(" ")[0] ?? "fornecedor"} 👋</h1><div className="surface mt-6 flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="text-sm text-muted-foreground">Status do perfil</p><p className="font-medium">{account.vendorStatus?VENDOR_STATUS_LABELS[account.vendorStatus]:"Complete seu cadastro"}</p></div><Button asChild><Link to="/painel/perfil">Editar perfil</Link></Button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{l:"Visualizações",v:data?.v?.views??0,i:Eye},{l:"Leads recebidos",v:data?.leads??0,i:MessageCircle},{l:"Cliques no WhatsApp",v:data?.v?.whatsapp_clicks??0,i:MousePointer2},{l:"Avaliação",v:Number(data?.v?.rating??0).toFixed(1),i:Star}].map(x=><div className="surface p-5" key={x.l}><x.i className="size-5 text-gold"/><p className="mt-4 font-display text-3xl">{x.v}</p><p className="text-sm text-muted-foreground">{x.l}</p></div>)}</div><div className="surface mt-8 p-6"><h2 className="font-display text-2xl">Próximos passos</h2><p className="mt-2 text-sm text-muted-foreground">Mantenha fotos, preços e serviços atualizados para aumentar suas chances de contato.</p><div className="mt-4 flex gap-3"><Button asChild variant="outline"><Link to="/painel/leads">Ver leads</Link></Button><Button asChild variant="outline"><Link to="/painel/perfil">Completar perfil</Link></Button></div></div></div></AppShell>}
