import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { AccountGuard } from "@/components/account-guard";
import { AppShell } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { VENDOR_STATUS_LABELS } from "@/lib/noivahub";
export const Route=createFileRoute("/_authenticated/admin")({head:()=>({meta:[{title:"Administração — NoivaHub"},{name:"description",content:"Moderação de fornecedores e indicadores do NoivaHub."},{property:"og:title",content:"Administração — NoivaHub"},{property:"og:description",content:"Área administrativa do NoivaHub."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Admin});
function Admin(){return <AccountGuard>{a=>a.isAdmin?<AdminView/>:<div className="flex min-h-screen items-center justify-center"><div className="text-center"><h1 className="font-display text-4xl">Acesso restrito</h1><p className="mt-2 text-muted-foreground">Esta área é exclusiva para administradores.</p></div></div>}</AccountGuard>}
function AdminView(){const qc=useQueryClient();const{data}=useQuery({queryKey:["admin-overview"],queryFn:async()=>{const[{data:vendors},{count:users},{count:brides},{count:leads}]=await Promise.all([supabase.from("vendors").select("id,company_name,owner_name,city,state,status,created_at").order("created_at",{ascending:false}),supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("profiles").select("id",{count:"exact",head:true}).eq("type","bride"),supabase.from("leads").select("id",{count:"exact",head:true})]);return{vendors:vendors??[],users:users??0,brides:brides??0,leads:leads??0}}});async function status(id:string,status:"aprovado"|"rejeitado"|"suspenso"){const{error}=await supabase.from("vendors").update({status}).eq("id",id);if(error)toast.error(error.message);else{toast.success("Status atualizado.");qc.invalidateQueries({queryKey:["admin-overview"]})}}return <AppShell type="vendor"><div className="mx-auto max-w-6xl p-5 md:p-10"><h1 className="font-display text-4xl">Administração</h1><div className="mt-6 grid gap-4 sm:grid-cols-3">{[["Usuários",data?.users??0],["Noivas",data?.brides??0],["Leads",data?.leads??0]].map(([l,v])=><div className="surface p-5" key={l}><p className="font-display text-3xl">{v}</p><p className="text-sm text-muted-foreground">{l}</p></div>)}</div><h2 className="mt-10 font-display text-3xl">Moderação de fornecedores</h2><div className="mt-4 space-y-3">{(data?.vendors??[]).map(v=><div className="surface flex flex-col gap-4 p-4 md:flex-row md:items-center" key={v.id}><div className="flex-1"><p className="font-medium">{v.company_name}</p><p className="text-sm text-muted-foreground">{v.owner_name} · {v.city??"Sem cidade"}{v.state?` - ${v.state}`:""}</p><p className="mt-1 text-xs">{VENDOR_STATUS_LABELS[v.status]}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>status(v.id,"aprovado")}>Aprovar</Button><Button size="sm" variant="outline" onClick={()=>status(v.id,"rejeitado")}>Rejeitar</Button><Button size="sm" variant="destructive" onClick={()=>status(v.id,"suspenso")}>Suspender</Button></div></div>)}</div></div></AppShell>}
