import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useEffect,useState } from "react";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { AccountGuard } from "@/components/account-guard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
export const Route=createFileRoute("/_authenticated/painel/perfil")({head:()=>({meta:[{title:"Editar perfil profissional — NoivaHub"},{name:"description",content:"Atualize os dados públicos do seu negócio."},{property:"og:title",content:"Editar perfil profissional — NoivaHub"},{property:"og:description",content:"Seu perfil profissional no NoivaHub."}]}),component:Page});function Page(){return <AccountGuard type="vendor">{a=><Editor id={a.vendorId}/>}</AccountGuard>}
function Editor({id}:{id:string|null}){const {data:cats=[]}=useQuery({queryKey:["cats"],queryFn:async()=>{const{data}=await supabase.from("categories").select("id,name").eq("active",true).order("name");return data??[]}});const {data:v}=useQuery({queryKey:["edit-vendor",id],enabled:!!id,queryFn:async()=>{const{data}=await supabase.from("vendors").select("*").eq("id",id??"").single();return data}});const [f,setF]=useState({company_name:"",owner_name:"",description:"",city:"",state:"",whatsapp:"",instagram:"",website:"",price_from:"",price_to:"",cover_url:"",logo_url:"",primary_category_id:""});useEffect(()=>{if(v)setF({company_name:v.company_name,owner_name:v.owner_name??"",description:v.description??"",city:v.city??"",state:v.state??"",whatsapp:v.whatsapp??"",instagram:v.instagram??"",website:v.website??"",price_from:String(v.price_from??""),price_to:String(v.price_to??""),cover_url:v.cover_url??"",logo_url:v.logo_url??"",primary_category_id:v.primary_category_id??""})},[v]);async function save(){if(!id||!f.company_name.trim()){toast.error("Informe o nome da empresa.");return}const{error}=await supabase.from("vendors").update({...f,company_name:f.company_name.trim(),price_from:f.price_from?Number(f.price_from):null,price_to:f.price_to?Number(f.price_to):null,primary_category_id:f.primary_category_id||null,status:v?.status==="rejeitado"?"pendente":v?.status}).eq("id",id);error?toast.error(error.message):toast.success("Perfil atualizado.")}return <AppShell type="vendor"><div className="mx-auto max-w-4xl p-5 md:p-10"><h1 className="font-display text-4xl">Perfil profissional</h1><p className="mt-2 text-muted-foreground">Estas informações aparecem para as noivas após a aprovação.</p><div className="surface mt-6 grid gap-5 p-6 sm:grid-cols-2">{[["company_name","Nome da empresa"],["owner_name","Responsável"],["city","Cidade"],["state","Estado (UF)"],["whatsapp","WhatsApp"],["instagram","Instagram"],["website","Site"],["cover_url","URL da foto de capa"],["logo_url","URL do logo"],["price_from","Preço a partir de"],["price_to","Preço até"]].map(([k,l])=><div key={k}><Label>{l}</Label><Input value={f[k as keyof typeof f]} onChange={e=>setF({...f,[k]:e.target.value})}/></div>)}<div><Label>Categoria principal</Label><Select value={f.primary_category_id} onValueChange={x=>setF({...f,primary_category_id:x})}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{cats.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div><div className="sm:col-span-2"><Label>Descrição</Label><Textarea rows={6} maxLength={2000} value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></div><Button onClick={save} className="sm:col-span-2">Salvar alterações</Button></div></div></AppShell>}
