/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated.assinatura'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated.contatos'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated.favoritos'
import { Route as AuthenticatedMeuCasamentoRouteImport } from './routes/_authenticated.meu-casamento'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated.meu-perfil'
import { Route as AuthenticatedNoivaRouteImport } from './routes/_authenticated.noiva'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated.painel'
import { Route as FornecedorSlugRouteImport } from './routes/fornecedor.$slug'
import { Route as FornecedoresIndexRouteImport } from './routes/fornecedores.index'
import { Route as FornecedoresCategoriaRouteImport } from './routes/fornecedores.$categoria'
import { Route as AuthenticatedPainelLeadsRouteImport } from './routes/_authenticated.painel.leads'\nimport { Route as AuthenticatedPainelEstatisticasRouteImport } from './routes/_authenticated.painel.estatisticas'\nimport { Route as AuthenticatedPainelConfiguracoesRouteImport } from './routes/_authenticated.painel.configuracoes'
import { Route as AuthenticatedPainelPerfilRouteImport } from './routes/_authenticated.painel.perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuCasamentoRoute =
  AuthenticatedMeuCasamentoRouteImport.update({
    id: '/meu-casamento',
    path: '/meu-casamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNoivaRoute = AuthenticatedNoivaRouteImport.update({
  id: '/noiva',
  path: '/noiva',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FornecedorSlugRoute = FornecedorSlugRouteImport.update({
  id: '/fornecedor/$slug',
  path: '/fornecedor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresIndexRoute = FornecedoresIndexRouteImport.update({
  id: '/fornecedores/',
  path: '/fornecedores/',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresCategoriaRoute = FornecedoresCategoriaRouteImport.update({
  id: '/fornecedores/$categoria',
  path: '/fornecedores/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelLeadsRoute =
  AuthenticatedPainelLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEstatisticasRoute = AuthenticatedPainelEstatisticasRouteImport.update({ id: '/estatisticas', path: '/estatisticas', getParentRoute: () => AuthenticatedPainelRoute } as any)\nconst AuthenticatedPainelConfiguracoesRoute = AuthenticatedPainelConfiguracoesRouteImport.update({ id: '/configuracoes', path: '/configuracoes', getParentRoute: () => AuthenticatedPainelRoute } as any)\nconst AuthenticatedPainelPerfilRoute =
  AuthenticatedPainelPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/meu-casamento': typeof AuthenticatedMeuCasamentoRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/noiva': typeof AuthenticatedNoivaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/fornecedor/$slug': typeof FornecedorSlugRoute
  '/fornecedores/$categoria': typeof FornecedoresCategoriaRoute
  '/fornecedores/': typeof FornecedoresIndexRoute
  '/painel/leads': typeof AuthenticatedPainelLeadsRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute\n  '/painel/estatisticas': typeof AuthenticatedPainelEstatisticasRoute\n  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute\n  '/painel/estatisticas': typeof AuthenticatedPainelEstatisticasRoute\n  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/meu-casamento': typeof AuthenticatedMeuCasamentoRoute
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/noiva': typeof AuthenticatedNoivaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/fornecedor/$slug': typeof FornecedorSlugRoute
  '/fornecedores/$categoria': typeof FornecedoresCategoriaRoute
  '/fornecedores': typeof FornecedoresIndexRoute
  '/painel/leads': typeof AuthenticatedPainelLeadsRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute\n  '/painel/estatisticas': typeof AuthenticatedPainelEstatisticasRoute\n  '/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/meu-casamento': typeof AuthenticatedMeuCasamentoRoute
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/noiva': typeof AuthenticatedNoivaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/fornecedor/$slug': typeof FornecedorSlugRoute
  '/fornecedores/$categoria': typeof FornecedoresCategoriaRoute
  '/fornecedores/': typeof FornecedoresIndexRoute
  '/_authenticated/painel/leads': typeof AuthenticatedPainelLeadsRoute
  '/_authenticated/painel/perfil': typeof AuthenticatedPainelPerfilRoute\n  '/_authenticated/painel/estatisticas': typeof AuthenticatedPainelEstatisticasRoute\n  '/_authenticated/painel/configuracoes': typeof AuthenticatedPainelConfiguracoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/precos'
    | '/reset-password'
    | '/admin'
    | '/assinatura'
    | '/contatos'
    | '/favoritos'
    | '/meu-casamento'
    | '/meu-perfil'
    | '/noiva'
    | '/onboarding'
    | '/painel'
    | '/fornecedor/$slug'
    | '/fornecedores/$categoria'
    | '/fornecedores/'
    | '/painel/leads'
    | '/painel/perfil'\n    | '/painel/estatisticas'\n    | '/painel/configuracoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/precos'
    | '/reset-password'
    | '/admin'
    | '/assinatura'
    | '/contatos'
    | '/favoritos'
    | '/meu-casamento'
    | '/meu-perfil'
    | '/noiva'
    | '/onboarding'
    | '/painel'
    | '/fornecedor/$slug'
    | '/fornecedores/$categoria'
    | '/fornecedores'
    | '/painel/leads'
    | '/painel/perfil'\n    | '/painel/estatisticas'\n    | '/painel/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/precos'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/assinatura'
    | '/_authenticated/contatos'
    | '/_authenticated/favoritos'
    | '/_authenticated/meu-casamento'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/noiva'
    | '/_authenticated/onboarding'
    | '/_authenticated/painel'
    | '/fornecedor/$slug'
    | '/fornecedores/$categoria'
    | '/fornecedores/'
    | '/_authenticated/painel/leads'
    | '/_authenticated/painel/perfil'\n    | '/_authenticated/painel/estatisticas'\n    | '/_authenticated/painel/configuracoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrecosRoute: typeof PrecosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  FornecedorSlugRoute: typeof FornecedorSlugRoute
  FornecedoresCategoriaRoute: typeof FornecedoresCategoriaRoute
  FornecedoresIndexRoute: typeof FornecedoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-casamento': {
      id: '/_authenticated/meu-casamento'
      path: '/meu-casamento'
      fullPath: '/meu-casamento'
      preLoaderRoute: typeof AuthenticatedMeuCasamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/noiva': {
      id: '/_authenticated/noiva'
      path: '/noiva'
      fullPath: '/noiva'
      preLoaderRoute: typeof AuthenticatedNoivaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/fornecedor/$slug': {
      id: '/fornecedor/$slug'
      path: '/fornecedor/$slug'
      fullPath: '/fornecedor/$slug'
      preLoaderRoute: typeof FornecedorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores/': {
      id: '/fornecedores/'
      path: '/fornecedores'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof FornecedoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores/$categoria': {
      id: '/fornecedores/$categoria'
      path: '/fornecedores/$categoria'
      fullPath: '/fornecedores/$categoria'
      preLoaderRoute: typeof FornecedoresCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/leads': {
      id: '/_authenticated/painel/leads'
      path: '/leads'
      fullPath: '/painel/leads'
      preLoaderRoute: typeof AuthenticatedPainelLeadsRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/estatisticas': { id: '/_authenticated/painel/estatisticas'; path: '/estatisticas'; fullPath: '/painel/estatisticas'; preLoaderRoute: typeof AuthenticatedPainelEstatisticasRouteImport; parentRoute: typeof AuthenticatedPainelRoute }\n    '/_authenticated/painel/configuracoes': { id: '/_authenticated/painel/configuracoes'; path: '/configuracoes'; fullPath: '/painel/configuracoes'; preLoaderRoute: typeof AuthenticatedPainelConfiguracoesRouteImport; parentRoute: typeof AuthenticatedPainelRoute }\n    '/_authenticated/painel/perfil': {
      id: '/_authenticated/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof AuthenticatedPainelPerfilRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelLeadsRoute: typeof AuthenticatedPainelLeadsRoute
  AuthenticatedPainelPerfilRoute: typeof AuthenticatedPainelPerfilRoute\n  AuthenticatedPainelEstatisticasRoute: typeof AuthenticatedPainelEstatisticasRoute\n  AuthenticatedPainelConfiguracoesRoute: typeof AuthenticatedPainelConfiguracoesRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelLeadsRoute: AuthenticatedPainelLeadsRoute,
  AuthenticatedPainelPerfilRoute: AuthenticatedPainelPerfilRoute,\n  AuthenticatedPainelEstatisticasRoute: AuthenticatedPainelEstatisticasRoute,\n  AuthenticatedPainelConfiguracoesRoute: AuthenticatedPainelConfiguracoesRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedMeuCasamentoRoute: typeof AuthenticatedMeuCasamentoRoute
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedNoivaRoute: typeof AuthenticatedNoivaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedMeuCasamentoRoute: AuthenticatedMeuCasamentoRoute,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedNoivaRoute: AuthenticatedNoivaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrecosRoute: PrecosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  FornecedorSlugRoute: FornecedorSlugRoute,
  FornecedoresCategoriaRoute: FornecedoresCategoriaRoute,
  FornecedoresIndexRoute: FornecedoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
